spring:
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    request-context-attribute: request
    expose-session-attributes: true
    expose-request-attributes: true
    suffix: .ftl